# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 426899bd830ab03e4e3ea8ba1e5a4ea97431bd917738f2a8999a8027bbfec50ddcf66b54a8eb8802c28b29194ce06ec57a5c3dd46309a35b392b854ca7e84c1a

test:
  secret_key_base: 1f62add08edd5a7715e88e7fb7d7dab092e66ee2b2bd30ce9ee17b8009aa61b02b87bf69b9e4e5d504ad668b8c90b5447568c94ab7cd762084468eb690207e80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
